# 无人机配置（匹配CARIC-RL环境）
drone:  
  model_name: "hummingbird"  # 匹配代码中的无人机模型
  
  # 物理参数
  mass: 1.5  # kg
  max_thrust: 20.0  # N
  
  # 控制限制
  max_velocity: 3.0  # m/s
  max_angular_velocity: 1.5  # rad/s

# 传感器配置（匹配env.py中的传感器设置）
sensor:
  # LiDAR配置（用于CARIC建图和障碍物检测）
  lidar_range: 20.0  # 20米检测范围（匹配代码中的lidar_range）
  lidar_vfov: [-30, 30]  # 垂直视野范围（匹配代码中的lidar_vfov）
  lidar_vbeams: 16  # 垂直光束数量（匹配代码中的lidar_vbeams）
  lidar_hres: 2.0  # 水平分辨率度数（匹配代码中的lidar_hres）
  
  # 相机配置（用于兴趣点扫描）
  camera_fov: 60.0  # 相机视野角度（匹配代码中的camera_fov）
  camera_range: 15.0  # 相机检测距离（匹配代码中的camera_range）
  camera_resolution: [640, 480]  # 相机分辨率

# CARIC特定参数（匹配环境代码）
caric:
  voxel_size: 0.5  # 体素大小（匹配代码中的voxel_size）
  exploration_threshold: 0.8  # 探索完成阈值
  scan_completion_distance: 3.0  # 扫描完成距离
  edge_detection_threshold: 0.3  # 边缘检测阈值
  corner_detection_threshold: 0.5  # 角点检测阈值
